### ISSUE TITLE
can't compile due to missing python26 dependancy

### ISSUE THREAD

**Issue by khang06** [google/syzygy#64]
sorry if this is the wrong place to report this bug, i'm not very familiar with how google does issues with their projects...

so i followed the instructions in https://github.com/google/syzygy/wiki/SyzygyDevelopmentGuide (depot_tools cloned, added to path, etc) and there seems to be a problem with the build process

```
D:\depot_tools\szygy>fetch syzygy
Running: 'C:\Python27\python.exe' 'D:\depot_tools\gclient.py' root
Running: 'C:\Python27\python.exe' 'D:\depot_tools\gclient.py' config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/syzygy",
    "managed": False,
    "name": "src",
    "deps_file": "DEPS",
  },
]
'
Running: 'C:\Python27\python.exe' 'D:\depot_tools\gclient.py' sync

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/syzygy D:\depot_tools\szygy\_gclient_src_htdvrk' in 'D:\depot_tools\szygy'
Cloning into 'D:\depot_tools\szygy\_gclient_src_htdvrk'...
remote: Sending approximately 337.79 MiB ...
remote: Total 39255 (delta 31367), reused 39255 (delta 31367)
Receiving objects: 100% (39255/39255), 337.79 MiB | 47.57 MiB/s, done.
Resolving deltas: 100% (31367/31367), done.
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/python_26" "D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u"' in D:\depot_tools\szygy failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/python_26" "D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u"' in D:\depot_tools\szygy failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/python_26" "D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u"' in D:\depot_tools\szygy failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/deps/python_26" "D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u"' in D:\depot_tools\szygy failed; will retry after a short nap...
Syncing projects:  80% (17/21) src/third_party/icu

src/third_party/python_26 (ERROR)
----------------------------------------
[0:00:25] Started.
[0:00:25]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/deps/python_26 D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u' in 'D:\depot_tools\szygy'
[0:00:25] Cloning into 'D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u'...
[0:00:26] fatal: remote error: Git repository not found

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/deps/python_26 D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u' in 'D:\depot_tools\szygy'
[0:00:27] Cloning into 'D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u'...
[0:00:27] fatal: remote error: Git repository not found

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/deps/python_26 D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u' in 'D:\depot_tools\szygy'
[0:00:29] Cloning into 'D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u'...
[0:00:29] fatal: remote error: Git repository not found

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/deps/python_26 D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u' in 'D:\depot_tools\szygy'
[0:00:32] Cloning into 'D:\depot_tools\szygy\src\third_party\_gclient_python_26_xdir2u'...
[0:00:32] fatal: remote error: Git repository not found
Traceback (most recent call last):
  File "D:\depot_tools\gclient_scm.py", line 1054, in _Clone
    print_stdout=print_stdout, stdout=stdout)
  File "D:\depot_tools\gclient_scm.py", line 1378, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "D:\depot_tools\gclient_utils.py", line 344, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "D:\depot_tools\gclient_utils.py", line 606, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/deps/python_26 D:\\depot_tools\\szygy\\src\\third_party\\_gclient_python_26_xdir2u' returned non-zero exit status 128 in D:\depot_tools\szygy
[0:00:37] _____ Conflicting directory found in D:\depot_tools\szygy\src\third_party\python_26. Moving to D:\depot_tools\szygy\_bad_scm\src\third_party\python_26ctfmkq.
----------------------------------------


Warnings:
Conflicting directory D:\depot_tools\szygy\src\third_party\python_26 moved to D:\depot_tools\szygy\_bad_scm\src\third_party\python_26ctfmkq.
Traceback (most recent call last):
  File "D:\depot_tools\metrics.py", line 266, in print_notice_and_exit
    yield
  File "D:\depot_tools\gclient.py", line 3155, in <module>
    sys.exit(main(sys.argv[1:]))
  File "D:\depot_tools\gclient.py", line 3141, in main
    return dispatcher.execute(OptionParser(), argv)
  File "D:\depot_tools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "D:\depot_tools\gclient.py", line 2699, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "D:\depot_tools\gclient.py", line 1734, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "D:\depot_tools\gclient_utils.py", line 894, in flush
    reraise(e[0], e[1], e[2])
  File "D:\depot_tools\gclient_utils.py", line 971, in run
    self.item.run(*self.args, **self.kwargs)
  File "D:\depot_tools\gclient.py", line 910, in run
    file_list)
  File "D:\depot_tools\gclient_scm.py", line 133, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "D:\depot_tools\gclient_scm.py", line 559, in update
    self._DeleteOrMove(options.force)
  File "D:\depot_tools\gclient_scm.py", line 208, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "C:\Python27\lib\shutil.py", line 316, in move
    copy2(src, real_dst)
  File "C:\Python27\lib\shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'D:\\depot_tools\\szygy\\src\\third_party\\python_26'
Subprocess failed with return code 1.
```

the fetch script appears to try cloning `https://chromium.googlesource.com/chromium/deps/python_26`, but nothing exists at that url. the entire /deps/ repository appears to be empty when cloned on my end

**Comment by chhamilton** [comment]
Unfortunately, Syzygy is deprecated and currently unmaintained. The Python 2.6 dependency was simply so that we could have a hermetic build environment, but realistically any Python 2.6 or 2.7 environment locally installed should do. You'll simply have to make sure that the build environment can find the installation at the appropriate location.

**Comment by chengshulei** [comment]
I fixed the issue,it need modify the file:  
**.\syzygy\src\DEP**
```
"src/third_party/python_26":
    "https://github.com/bpsinc-native/python_26.git@5bb4080", 
```
https://chromium.googlesource.com/chromium/deps/python_26 is bad,
it can use https://github.com/bpsinc-native/python_26.git@5bb4080  to instead.
